#!/bin/bash
# Set things up for EC2 management
# Create a key pair and save to KEYDIR
# Create a security group for launching EC2 instances

source ec2.cfg

if [ -r $KEY_FILE ]; then
    echo "$KEY_FILE exists; skipping creation of new keypair"
else
    aws ec2 create-key-pair --key-name $KEY --query 'KeyMaterial' --output text > $KEY_FILE
    chmod 400 $KEY_FILE
    echo "created: $KEY_FILE"
fi

# Could automate SG creation, but just use a known good one for now.  It's trivial.
if ! aws ec2 describe-security-groups --group-ids $SG > /dev/null 2>&1; then
    echo "Unable to find pre-defined security group $SG"
    exit 1
fi
echo "Security Group OK"

#VPC=vpc-de9c60bb
#SG_NAME=ScaleGroup
#SG_DESC="ScaleTest"
#aws ec2 create-security-group --group-name $SG_NAME --description $SG_DESC --vpc-id $VPC