#!/bin/bash
# Launch N instances

source ec2.cfg

ec2-run-instances $AMI -t $INST_TYPE -n $INST_COUNT -k $KEY -g $SG -s $SUBNET 

echo "Launched instances:"
ec2din -F key-name=$KEY | awk '/INSTANCE/ {print $2}'
